<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413130242 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE historial_movimiento ADD usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE historial_movimiento ADD CONSTRAINT FK_39639800DB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_39639800DB38439E ON historial_movimiento (usuario_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE historial_movimiento DROP CONSTRAINT FK_39639800DB38439E');
        $this->addSql('DROP INDEX IDX_39639800DB38439E');
        $this->addSql('ALTER TABLE historial_movimiento DROP usuario_id');
    }
}
